[package]
name = "llama-cpp-sys"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake = "0.1"
bindgen = "0.64.0"

[dev-dependencies]
rand = "0.8.5"
